Environment variables for BinTray added
test-editor/xtext-dropwizard pull request #47
Opened 2018-10-22 08:56 UTC by kbayraktar

Gradle SHASUM version updated

2018-10-22 08:58 UTC, kbayraktar commented
Please delete the environment variables from repository settings on travis before merging this branch into master !

2018-10-22 14:34 UTC, kbayraktar commented
Please merge this project not until you delete the old repository environment variables settings on travis.

2018-10-23 07:45 UTC, jjelschen commented on .travis.yml
> +  -a /etc/nix/nix.conf > /dev/null
accidental line break…?

2018-10-23 07:46 UTC, jjelschen requested changes
please double-check, there's a newline that I think will break the script.

2018-10-23 08:36 UTC, jjelschen approved these changes

2018-10-23 08:38 UTC, merged